version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      reviewers:
          - koconder
    - package-ecosystem: pip
      directory: /
      schedule:
          interval: weekly
      reviewers:
          - koconder
