default_language_version:
    python: python3.9

repos:
    # Security
    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.16.3
      hooks:
          - id: gitleaks

    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.4.0
      hooks:
          - id: detect-secrets
            args: [--exclude-files, .*\.ipynb$, .*.md$]
          - id: detect-secrets
            name: detect-secrets-jupyter
            args: [--exclude-files, '.*[^i][^p][^y][^n][^b]$', --exclude-lines, '"(hash|id|image/\w+)":.*']

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
          - id: bandit

    # Standard Checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: check-toml
          - id: debug-statements

    # YAML
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.31.0
      hooks:
          - id: yamllint
            args: [-c=.yamllint]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
            # this removes the '---' top of each yml file
            args: [--implicit_start]

    # SQL
    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 2.0.7
      hooks:
          - id: sqlfluff-lint
            files: \.sql$
            # args: [--dialect, ansi]

    # Markdown
    - repo: https://github.com/executablebooks/mdformat
      rev: 0.7.16
      hooks:
          - id: mdformat

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black]

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py3-plus, --py38-plus]

    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.2.0
      hooks:
          - id: mypy
            exclude: ^tests/
            args: [--no-strict-optional, --ignore-missing-imports]
            additional_dependencies:
                - lxml
                - numpy
                - pandas
                - requests
                - torch
                - scikit-learn
                - types-pytz

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear==22.10.27
                - flake8-bandit==4.1.1
                - flake8-builtins==2.0.1
                - flake8-local-import==1.0.6
