name: No Out of Hours Merge
description: Block PR merges outside business hours, holidays and other specific time windows.
author: Vincent Koc
branding:
    icon: thumbs-down
    color: red
inputs:
    GITHUB_TOKEN:
        description: GitHub token
        required: true
    PR_TITLE:
        description: Title of the pull request (if you want check for hotfix)
        required: true
    TIMEZONE:
        description: Timezone to use for checking the current time
        required: false
        default: Europe/London
    RESTRICTED_TIMES:
        description: A JSON object containing restricted times based on weekdays, or specific dates or holidays
        required: false
        default: >
            {
              "weekly": [
                {
                  "days": ["mon", "tue", "wed", "thu", "fri"],
                  "intervals": [[0, 7], [16.5, 24]]
                }
              ],
              "dates": [
                {
                  "date": "2023-12-25",
                  "intervals": [[0, 24]]
                }
              ],
              "holidays": {
                "country": "GB",
                "state": "UK",
                "intervals": [[0, 24]]
              }
            }
    CUSTOM_MESSAGE:
        description: Custom message to be posted as a comment on the PR if merging is not allowed
        required: false
    CHECK_EXISTING_COMMENT:
        description: Boolean flag to enable/disable checking for existing comment with the same message
        required: false
        default: 'true'
runs:
    using: docker
    image: Dockerfile
