name: Test No Out Hours Merge Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests

    - name: Test Restrict PR Merge Action
      uses: ./  # Use an action in the same repository
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TIMEZONE: "Australia/Sydney"
        RESTRICTED_TIMES: '{"mon": [(0, 9), (17, 24)], "tue": [(0, 9), (17, 24)], "wed": [(0, 9), (17, 24)], "thu": [(0, 9), (17, 24)], "fri": [(0, 9), (17, 24)], "sat": [(0, 24)], "sun": [(0, 24)]}'
        CUSTOM_MESSAGE: "⚠️ **PR merging is not allowed outside business hours.** ⚠️"
        CHECK_EXISTING_COMMENT: "true"
