name: Test No Weekend Merge Action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: No Weekend Merge
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: ${{ env.CI_PR_TITLE }}
